# Generated by Django 4.0.4 on 2022-05-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dateـofـbirth',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Date of birth'),
        ),
    ]
