# Generated by Django 4.0.4 on 2022-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
