# Generated by Django 4.0.4 on 2022-05-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Derakhti', '0008_alter_contract_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=99, verbose_name='First name')),
                ('last_name', models.CharField(max_length=99, verbose_name='Last name')),
                ('accountـnumber', models.IntegerField(verbose_name='Account number')),
                ('shaba_number', models.IntegerField(verbose_name='Shaba number')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
