# Generated by Django 4.0.4 on 2022-05-07 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Derakhti', '0009_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Contracts',
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
