# Generated by Django 4.0.4 on 2022-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0010_rename_contract_contracts_alter_mainuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='identifierـcode',
            field=models.CharField(max_length=30, verbose_name='Identifier code'),
        ),
    ]
