# Generated by Django 4.0.4 on 2022-05-07 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Derakhti', '0011_alter_mainuser_identifierـcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mainUser_admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
    ]
