# Generated by Django 4.0.4 on 2022-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0012_mainuser_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='r_or_l',
            field=models.BooleanField(default=False, verbose_name='Ruser or Luser'),
        ),
    ]
