# Generated by Django 4.0.4 on 2022-05-10 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Derakhti', '0014_mainuser_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerakhtiProductMainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProductMainCategoriesImage', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='DerakhtiProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999, verbose_name='Title')),
                ('slug', models.CharField(max_length=999, verbose_name='Slug')),
                ('descriptions', models.CharField(max_length=999, verbose_name='Descriptions')),
                ('image', models.ImageField(upload_to='Products', verbose_name='Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Products', verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Products', verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Products', verbose_name='Image3')),
                ('price', models.IntegerField(default=0)),
                ('volume', models.CharField(max_length=999, verbose_name='Volume')),
                ('compounds', models.CharField(max_length=999, verbose_name='Compounds')),
                ('licenseـissuer', models.CharField(max_length=999, verbose_name='License issuer')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('limit', models.IntegerField(default=0, verbose_name='Limit')),
                ('status', models.BooleanField(default=True)),
                ('maincategories', models.ManyToManyField(to='Derakhti.derakhtiproductmaincategories', verbose_name='Main Category')),
            ],
        ),
        migrations.CreateModel(
            name='DerakhtiProductsCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Payment Date')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shoper')),
            ],
        ),
        migrations.CreateModel(
            name='DerakhtiProductSubCategories_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='DerakhtiProductSubCategories_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('sub_categories2', models.ManyToManyField(blank=True, to='Derakhti.derakhtiproductsubcategories_2', verbose_name='Sub Categories 2')),
            ],
        ),
        migrations.CreateModel(
            name='DerakhtiProductsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Derakhti.derakhtiproductscarts', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Derakhti.derakhtiproducts', verbose_name='Product ')),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='shopper')),
            ],
        ),
        migrations.CreateModel(
            name='DerakhtiProductsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Derakhti.derakhtiproducts', verbose_name='Prodcut Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='derakhtiproducts',
            name='subCategories1',
            field=models.ManyToManyField(to='Derakhti.derakhtiproductsubcategories_1', verbose_name='Sub Category 1'),
        ),
        migrations.AddField(
            model_name='derakhtiproducts',
            name='subCategories2',
            field=models.ManyToManyField(to='Derakhti.derakhtiproductsubcategories_2', verbose_name='Sub Category 2'),
        ),
        migrations.AddField(
            model_name='derakhtiproducts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USer'),
        ),
        migrations.AddField(
            model_name='derakhtiproductmaincategories',
            name='sub_categories1',
            field=models.ManyToManyField(blank=True, to='Derakhti.derakhtiproductsubcategories_1', verbose_name='Sub Categories 1'),
        ),
    ]
