# Generated by Django 4.0.4 on 2022-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0015_derakhtiproductmaincategories_derakhtiproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='derakhtiproducts',
            name='vocher',
            field=models.BooleanField(default=True),
        ),
    ]
