# Generated by Django 4.0.4 on 2022-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Derakhti', '0017_remove_mainuser_identifierـcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='places',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Places'),
        ),
    ]
