# Generated by Django 4.0.4 on 2022-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProductMainCategoriesImage', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductsSlides', verbose_name='Image')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategories_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategories_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('sub_categories2', models.ManyToManyField(blank=True, to='Taksathi.productsubcategories_2', verbose_name='Sub Categories 2')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999, verbose_name='Title')),
                ('slug', models.CharField(max_length=999, verbose_name='Slug')),
                ('descriptions', models.CharField(max_length=999, verbose_name='Descriptions')),
                ('image', models.ImageField(upload_to='Products', verbose_name='Image')),
                ('price', models.IntegerField(default=0)),
                ('volume', models.CharField(max_length=999, verbose_name='Volume')),
                ('compounds', models.CharField(max_length=999, verbose_name='Compounds')),
                ('licenseـissuer', models.CharField(max_length=999, verbose_name='License issuer')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('maincategories', models.ManyToManyField(to='Taksathi.productmaincategories', verbose_name='Main Category')),
                ('subCategories1', models.ManyToManyField(to='Taksathi.productsubcategories_1', verbose_name='Sub Category 1')),
                ('subCategories2', models.ManyToManyField(to='Taksathi.productsubcategories_2', verbose_name='Sub Category 2')),
            ],
        ),
        migrations.AddField(
            model_name='productmaincategories',
            name='sub_categories1',
            field=models.ManyToManyField(blank=True, to='Taksathi.productsubcategories_1', verbose_name='Sub Categories 1'),
        ),
    ]
