# Generated by Django 4.0.4 on 2022-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taksathi', '0003_alter_tiket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
