# Generated by Django 4.0.4 on 2022-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taksathi', '0004_alter_tiket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='limit',
            field=models.IntegerField(default=0, verbose_name='Limit'),
        ),
    ]
