# Generated by Django 4.0.4 on 2022-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taksathi', '0009_alter_products_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorders',
            name='payment_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Payment Date'),
        ),
    ]
