# Generated by Django 4.0.4 on 2022-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taksathi', '0011_products_image1_products_image2_products_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorders',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Payment Date'),
        ),
    ]
