# Generated by Django 4.0.4 on 2022-05-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Taksathi', '0012_alter_productsorders_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsorders',
            name='shopper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='shopper'),
        ),
    ]
