# Generated by Django 4.0.4 on 2022-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taksathi', '0013_productsorders_shopper'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_suppot',
            field=models.BooleanField(default=False, verbose_name='Is Support'),
        ),
    ]
